package tech.hanasaki.momotalk_plus.core.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.ui.graphics.Color
import tech.hanasaki.momotalk_plus.app.ui.theme.*

data class AppTheme(
    val id: String,
    val name: String,
    val colorScheme: ColorScheme,
    val chatBubbleSent: Color,
    val chatBubbleReceived: Color,
    val backgroundImage: String? = null,
)

object PredefinedThemes {
    val Default = AppTheme(
        id = "light",
        name = "默认主题",
        colorScheme = androidx.compose.material3.lightColorScheme(
            primary = primaryLight,
            onPrimary = onPrimaryLight,
            primaryContainer = primaryContainerLight,
            onPrimaryContainer = onPrimaryContainerLight,
            secondary = secondaryLight,
            onSecondary = onSecondaryLight,
            secondaryContainer = secondaryContainerLight,
            onSecondaryContainer = onSecondaryContainerLight,
            tertiary = tertiaryLight,
            onTertiary = onTertiaryLight,
            tertiaryContainer = tertiaryContainerLight,
            onTertiaryContainer = onTertiaryContainerLight,
            error = errorLight,
            onError = onErrorLight,
            errorContainer = errorContainerLight,
            onErrorContainer = onErrorContainerLight,
            background = backgroundLight,
            onBackground = onBackgroundLight,
            surface = surfaceLight,
            onSurface = onSurfaceLight,
            surfaceVariant = surfaceVariantLight,
            onSurfaceVariant = onSurfaceVariantLight,
            outline = outlineLight,
            outlineVariant = outlineVariantLight,
            scrim = scrimLight,
            inverseSurface = inverseSurfaceLight,
            inverseOnSurface = inverseOnSurfaceLight,
            inversePrimary = inversePrimaryLight,
            surfaceDim = surfaceDimLight,
            surfaceBright = surfaceBrightLight,
            surfaceContainerLowest = surfaceContainerLowestLight,
            surfaceContainerLow = surfaceContainerLowLight,
            surfaceContainer = surfaceContainerLight,
            surfaceContainerHigh = surfaceContainerHighLight,
            surfaceContainerHighest = surfaceContainerHighestLight,
        ),
        chatBubbleSent = primaryLight,
        chatBubbleReceived = surfaceVariantLight
    )

    val Dark = AppTheme(
        id = "dark",
        name = "夜间模式",
        colorScheme = androidx.compose.material3.darkColorScheme(
            primary = primaryDark,
            onPrimary = onPrimaryDark,
            primaryContainer = primaryContainerDark,
            onPrimaryContainer = onPrimaryContainerDark,
            secondary = secondaryDark,
            onSecondary = onSecondaryDark,
            secondaryContainer = secondaryContainerDark,
            onSecondaryContainer = onSecondaryContainerDark,
            tertiary = tertiaryDark,
            onTertiary = onTertiaryDark,
            tertiaryContainer = tertiaryContainerDark,
            onTertiaryContainer = onTertiaryContainerDark,
            error = errorDark,
            onError = onErrorDark,
            errorContainer = errorContainerDark,
            onErrorContainer = onErrorContainerDark,
            background = backgroundDark,
            onBackground = onBackgroundDark,
            surface = surfaceDark,
            onSurface = onSurfaceDark,
            surfaceVariant = surfaceVariantDark,
            onSurfaceVariant = onSurfaceVariantDark,
            outline = outlineDark,
            outlineVariant = outlineVariantDark,
            scrim = scrimDark,
            inverseSurface = inverseSurfaceDark,
            inverseOnSurface = inverseOnSurfaceDark,
            inversePrimary = inversePrimaryDark,
            surfaceDim = surfaceDimDark,
            surfaceBright = surfaceBrightDark,
            surfaceContainerLowest = surfaceContainerLowestDark,
            surfaceContainerLow = surfaceContainerLowDark,
            surfaceContainer = surfaceContainerDark,
            surfaceContainerHigh = surfaceContainerHighDark,
            surfaceContainerHighest = surfaceContainerHighestDark,
        ),
        chatBubbleSent = primaryDark,
        chatBubbleReceived = surfaceVariantDark
    )

    val LightMediumContrast = AppTheme(
        id = "light_medium_contrast",
        name = "中等对比度",
        colorScheme = androidx.compose.material3.lightColorScheme(
            primary = primaryLightMediumContrast,
            onPrimary = onPrimaryLightMediumContrast,
            primaryContainer = primaryContainerLightMediumContrast,
            onPrimaryContainer = onPrimaryContainerLightMediumContrast,
            secondary = secondaryLightMediumContrast,
            onSecondary = onSecondaryLightMediumContrast,
            secondaryContainer = secondaryContainerLightMediumContrast,
            onSecondaryContainer = onSecondaryContainerLightMediumContrast,
            tertiary = tertiaryLightMediumContrast,
            onTertiary = onTertiaryLightMediumContrast,
            tertiaryContainer = tertiaryContainerLightMediumContrast,
            onTertiaryContainer = onTertiaryContainerLightMediumContrast,
            error = errorLightMediumContrast,
            onError = onErrorLightMediumContrast,
            errorContainer = errorContainerLightMediumContrast,
            onErrorContainer = onErrorContainerLightMediumContrast,
            background = backgroundLightMediumContrast,
            onBackground = onBackgroundLightMediumContrast,
            surface = surfaceLightMediumContrast,
            onSurface = onSurfaceLightMediumContrast,
            surfaceVariant = surfaceVariantLightMediumContrast,
            onSurfaceVariant = onSurfaceVariantLightMediumContrast,
            outline = outlineLightMediumContrast,
            outlineVariant = outlineVariantLightMediumContrast,
            scrim = scrimLightMediumContrast,
            inverseSurface = inverseSurfaceLightMediumContrast,
            inverseOnSurface = inverseOnSurfaceLightMediumContrast,
            inversePrimary = inversePrimaryLightMediumContrast,
        ),
        chatBubbleSent = primaryLightMediumContrast,
        chatBubbleReceived = surfaceVariantLightMediumContrast
    )

    val LightHighContrast = AppTheme(
        id = "light_high_contrast",
        name = "高对比度",
        colorScheme = androidx.compose.material3.lightColorScheme(
            primary = primaryLightHighContrast,
            onPrimary = onPrimaryLightHighContrast,
            primaryContainer = primaryContainerLightHighContrast,
            onPrimaryContainer = onPrimaryContainerLightHighContrast,
            secondary = secondaryLightHighContrast,
            onSecondary = onSecondaryLightHighContrast,
            secondaryContainer = secondaryContainerLightHighContrast,
            onSecondaryContainer = onSecondaryContainerLightHighContrast,
            tertiary = tertiaryLightHighContrast,
            onTertiary = onTertiaryLightHighContrast,
            tertiaryContainer = tertiaryContainerLightHighContrast,
            onTertiaryContainer = onTertiaryContainerLightHighContrast,
            error = errorLightHighContrast,
            onError = onErrorLightHighContrast,
            errorContainer = errorContainerLightHighContrast,
            onErrorContainer = onErrorContainerLightHighContrast,
            background = backgroundLightHighContrast,
            onBackground = onBackgroundLightHighContrast,
            surface = surfaceLightHighContrast,
            onSurface = onSurfaceLightHighContrast,
            surfaceVariant = surfaceVariantLightHighContrast,
            onSurfaceVariant = onSurfaceVariantLightHighContrast,
            outline = outlineLightHighContrast,
            outlineVariant = outlineVariantLightHighContrast,
            scrim = scrimLightHighContrast,
        ),
        chatBubbleSent = primaryLightHighContrast,
        chatBubbleReceived = surfaceVariantLightHighContrast
    )

    val allThemes = listOf(Default, Dark, LightMediumContrast, LightHighContrast)
}

